language: python
python:
  - "3.6.3"

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install pipenv"
  - 'pipenv install --deploy --system --dev'


# command to run tests
# script: "python manage.py test"